// <auto-generated />
using System;
using Ecommerce.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230929094834_complete migration")]
    partial class completemigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "History"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Art"
                        });
                });

            modelBuilder.Entity("Ecommerce.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Kathmandu",
                            Name = "Tech Solution",
                            PhoneNumber = "7853214965",
                            PostalCode = "44500",
                            State = "3",
                            StreetAddress = "Kapan"
                        },
                        new
                        {
                            Id = 2,
                            City = "Khotang",
                            Name = "IT Expert",
                            PhoneNumber = "74327756375",
                            PostalCode = "6501",
                            State = "1",
                            StreetAddress = "Dhumbaharai"
                        },
                        new
                        {
                            Id = 3,
                            City = "Bhaktapur",
                            Name = "Orchid",
                            PhoneNumber = "7427785745",
                            PostalCode = "4702",
                            State = "2",
                            StreetAddress = "Gausala"
                        });
                });

            modelBuilder.Entity("Ecommerce.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("Ecommerce.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("OrderHeader");
                });

            modelBuilder.Entity("Ecommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Author = "Alex Explorer",
                            CategoryId = 2,
                            Description = "Embark on thrilling adventures and explore the unknown. Get ready for a journey of a lifetime! Uncover hidden treasures, face formidable challenges, and triumph over adversity as you traverse uncharted territories. This book is your passport to excitement and discovery.",
                            ISBN = "ADV20239",
                            ListPrice = 110.0,
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.0,
                            Title = "Adventure Awaits"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Chef Gourmand",
                            CategoryId = 3,
                            Description = "Indulge in a world of gourmet flavors with our carefully crafted recipes. Elevate your culinary skills! From mouth-watering appetizers to decadent desserts, this cookbook offers a tantalizing array of dishes that will impress even the most discerning palates. Get ready to embark on a gastronomic journey like no other.",
                            ISBN = "GD202310",
                            ListPrice = 75.0,
                            Price = 65.0,
                            Price100 = 55.0,
                            Price50 = 60.0,
                            Title = "Gourmet Delights Cookbook"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Emma Serene",
                            CategoryId = 1,
                            Description = "Immerse yourself in mindful moments and find peace in the present. Discover the beauty of mindfulness. This guide is your companion to mindfulness, offering practical techniques to achieve tranquility in a chaotic world. Through focused breathing and self-awareness, you can attain a state of serene consciousness that will enhance your overall well-being.",
                            ISBN = "MM202311",
                            ListPrice = 90.0,
                            Price = 80.0,
                            Price100 = 70.0,
                            Price50 = 75.0,
                            Title = "Mindfulness Moments"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Artistic Soul",
                            CategoryId = 1,
                            Description = "Unleash your creativity and express yourself through art. Let your imagination run wild! This book is an invitation to explore the realms of artistic expression. Dive into the world of colors, shapes, and textures, and learn various techniques that will help you create awe-inspiring artworks. Discover the artist within you and set your creativity free.",
                            ISBN = "AE202312",
                            ListPrice = 85.0,
                            Price = 75.0,
                            Price100 = 65.0,
                            Price50 = 70.0,
                            Title = "Artistic Expression"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Fitness Enthusiast",
                            CategoryId = 2,
                            Description = "Achieve your fitness goals and sculpt your body with our comprehensive fitness guide. Be the best version of yourself! This fitness guide is a roadmap to a healthier, fitter you. Tailored workout plans, nutrition tips, and motivational advice will help you embark on a transformative fitness journey. Take the first step towards a better you.",
                            ISBN = "UFG202313",
                            ListPrice = 70.0,
                            Price = 60.0,
                            Price100 = 50.0,
                            Price50 = 55.0,
                            Title = "Ultimate Fitness Guide"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Mystery Historian",
                            CategoryId = 3,
                            Description = "Solve historical enigmas and uncover hidden truths. An intriguing journey through time awaits! Delve into the mysteries of history, decipher clues from the past, and unlock the secrets that have eluded historians for centuries. This book invites you to become a detective of the past, solving enigmas that will unravel fascinating historical narratives.",
                            ISBN = "HE202314",
                            ListPrice = 95.0,
                            Price = 85.0,
                            Price100 = 75.0,
                            Price50 = 80.0,
                            Title = "Historical Enigma"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Astronomy Aficionado",
                            CategoryId = 1,
                            Description = "Gaze at the stars and explore the mysteries of the cosmos. Let the wonders of the universe captivate you! In this celestial journey, you'll traverse the vast expanse of space, exploring distant galaxies, nebulae, and the awe-inspiring beauty of our cosmos. With stunning imagery and intriguing facts, this book is your portal to the wonders of the night sky.",
                            ISBN = "SD202315",
                            ListPrice = 80.0,
                            Price = 70.0,
                            Price100 = 60.0,
                            Price50 = 65.0,
                            Title = "Stargazer's Dream"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Green Thumb",
                            CategoryId = 3,
                            Description = "Create your garden oasis with our carefully curated collection of plants and garden decor. Transform your outdoor space! Dive into the world of gardening and landscaping with this collection. Discover a variety of plants, decorative elements, and expert tips to turn your garden into a serene oasis. Let your creativity bloom in your own backyard.",
                            ISBN = "GO202316",
                            ListPrice = 120.0,
                            Price = 100.0,
                            Price100 = 90.0,
                            Price50 = 95.0,
                            Title = "Garden Oasis Collection"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Wellness Warrior",
                            CategoryId = 2,
                            Description = "Kickstart your journey towards a healthier lifestyle with our specially curated starter pack. Embrace wellness! This starter pack is designed to set you on a path of holistic wellness. It includes essential tools, guides, and motivation to help you adopt a healthy lifestyle. Take charge of your well-being and embrace the journey to a healthier you.",
                            ISBN = "HLS202317",
                            ListPrice = 55.0,
                            Price = 45.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "Healthy Lifestyle Starter Pack"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Sci-Fi Enthusiast",
                            CategoryId = 1,
                            Description = "Embark on an epic science fiction odyssey and explore new worlds. Let your imagination take flight! Prepare for an intergalactic adventure in this sci-fi odyssey. Traverse through the cosmos, encounter extraterrestrial beings, and witness futuristic technologies. With gripping narratives and imaginative storytelling, this book will transport you to a realm of infinite possibilities.",
                            ISBN = "SFO202318",
                            ListPrice = 105.0,
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "Sci-Fi Odyssey"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Film Buff",
                            CategoryId = 3,
                            Description = "Relive the magic of classic movies with this curated collection. Enjoy movie nights like never before! Rediscover timeless cinematic masterpieces with this collection of classic movies. From unforgettable performances to iconic dialogues, these movies have stood the test of time and continue to captivate audiences of all ages.",
                            ISBN = "CMN202319",
                            ListPrice = 70.0,
                            Price = 60.0,
                            Price100 = 50.0,
                            Price50 = 55.0,
                            Title = "Classic Movie Night"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Nature Enthusiast",
                            CategoryId = 1,
                            Description = "Capture the beauty of nature with this artistic canvas collection. Bring the outdoors into your home! Immerse yourself in the beauty of nature through this collection of art canvases. Each piece captures the essence of natural landscapes, from serene forests to breathtaking seascapes. Let nature's beauty grace your walls and fill your living space with tranquility.",
                            ISBN = "NC202320",
                            ListPrice = 85.0,
                            Price = 75.0,
                            Price100 = 65.0,
                            Price50 = 70.0,
                            Title = "Nature's Canvas"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Adventure Seeker",
                            CategoryId = 2,
                            Description = "Plan your great escape and discover thrilling adventures. Turn your wanderlust into reality! Let your wanderlust take flight with this guide to great escapes. Whether you're dreaming of a tropical paradise, a mountain retreat, or an urban adventure, this book will help you plan the perfect getaway. It's time to turn your travel fantasies into unforgettable memories.",
                            ISBN = "TGE202321",
                            ListPrice = 95.0,
                            Price = 85.0,
                            Price100 = 75.0,
                            Price50 = 80.0,
                            Title = "The Great Escape"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Spa Lover",
                            CategoryId = 3,
                            Description = "Transform your home into a spa retreat with our soothing spa essentials. Relax, rejuvenate, and unwind! Create your own sanctuary of relaxation with our spa essentials. From aromatic candles to luxurious bath oils, immerse yourself in a world of tranquility and self-care. Let the stresses of the day melt away as you indulge in a spa-like experience within the comforts of your home.",
                            ISBN = "SSE202322",
                            ListPrice = 50.0,
                            Price = 40.0,
                            Price100 = 30.0,
                            Price50 = 35.0,
                            Title = "Soothing Spa Essentials"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Romance Connoisseur",
                            CategoryId = 1,
                            Description = "Indulge in timeless romance with this collection of classic love stories. Let love's magic enchant you! Immerse yourself in a world of passion and romance with this curated collection. These timeless love stories will tug at your heartstrings and transport you to a world where love conquers all. Discover the enchanting tales that have captured the hearts of generations.",
                            ISBN = "TRC202323",
                            ListPrice = 80.0,
                            Price = 70.0,
                            Price100 = 60.0,
                            Price50 = 65.0,
                            Title = "Timeless Romance Collection"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Yoga Enthusiast",
                            CategoryId = 2,
                            Description = "Find inner peace and balance with our yoga and mindfulness kit. Start your journey towards holistic wellness! Begin your path to holistic wellness with our yoga and mindfulness kit. Discover the transformative power of yoga and mindfulness practices that nurture your mind, body, and soul. Embrace a lifestyle of serenity and balance.",
                            ISBN = "YMK202324",
                            ListPrice = 65.0,
                            Price = 55.0,
                            Price100 = 45.0,
                            Price50 = 50.0,
                            Title = "Yoga and Mindfulness Kit"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Fantasy Artisan",
                            CategoryId = 1,
                            Description = "Dive into the world of fantasy with our exquisite art prints set. Let your imagination come alive! Immerse yourself in a realm of fantasy with this art prints set. Each print showcases fantastical creatures, mythical landscapes, and magical scenes that will transport you to a world beyond imagination. Let your walls tell a story of enchantment and wonder.",
                            ISBN = "FAPS202325",
                            ListPrice = 90.0,
                            Price = 80.0,
                            Price100 = 70.0,
                            Price50 = 75.0,
                            Title = "Fantasy Art Prints Set"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Kitchen Maestro",
                            CategoryId = 3,
                            Description = "Equip your kitchen with our essential cooking utensil starter pack. Cook like a pro and create delicious meals! Unleash your inner chef with this cooking utensil starter pack. From spatulas to measuring cups, we've curated the essential tools to elevate your culinary skills. Cook with precision and flair, and delight your taste buds with delectable creations.",
                            ISBN = "CUSP202326",
                            ListPrice = 75.0,
                            Price = 65.0,
                            Price100 = 55.0,
                            Price50 = 60.0,
                            Title = "Cooking Utensil Starter Pack"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Tech Enthusiast",
                            CategoryId = 2,
                            Description = "Stay at the cutting edge of technology with our tech innovator's toolkit. Explore and innovate with confidence! Embrace the future with our tech innovator's toolkit. Stay informed about the latest advancements, tools, and technologies that are shaping our world. Equip yourself with the knowledge to innovate, create, and lead in the fast-paced tech landscape.",
                            ISBN = "TIK202327",
                            ListPrice = 110.0,
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.0,
                            Title = "Tech Innovator's Toolkit"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Fashion Maven",
                            CategoryId = 1,
                            Description = "Revamp your wardrobe with our curated fashionista's essentials. Stay stylish and on-trend! Elevate your style with our fashionista's essentials. From chic apparel to statement accessories, this collection is designed for the trendsetter in you. Stay ahead of the fashion curve and make a statement wherever you go.",
                            ISBN = "FWE202328",
                            ListPrice = 120.0,
                            Price = 100.0,
                            Price100 = 90.0,
                            Price50 = 95.0,
                            Title = "Fashionista's Wardrobe Essentials"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Alex Explorer",
                            CategoryId = 2,
                            Description = "Continue your thrilling adventures and explore new territories. The journey of a lifetime continues! Unlock new mysteries and face even greater challenges as you venture into uncharted territories. This sequel to the Adventure Awaits series promises an adrenaline-pumping expedition like no other. Get ready for the next chapter of excitement and discovery.",
                            ISBN = "ADV20239-2",
                            ListPrice = 115.0,
                            Price = 100.0,
                            Price100 = 90.0,
                            Price50 = 95.0,
                            Title = "Adventure Awaits - Part 2"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Chef Extraordinaire",
                            CategoryId = 3,
                            Description = "Master the art of cooking with our comprehensive culinary guide. Elevate your skills to a professional level! Take your culinary skills to new heights with this in-depth guide to mastering the art of cooking. From knife techniques to flavor pairings, this book covers everything you need to become a true chef. Let the culinary journey begin!",
                            ISBN = "MCA202329",
                            ListPrice = 85.0,
                            Price = 75.0,
                            Price100 = 65.0,
                            Price50 = 70.0,
                            Title = "Mastering the Culinary Arts"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Empowerment Advocate",
                            CategoryId = 1,
                            Description = "Empower women and inspire change with our guide to women's empowerment. Celebrate the strength and resilience of women! This guide is a tribute to the remarkable achievements and contributions of women throughout history. It's a call to action to uplift, support, and empower women in all walks of life. Together, let's create a world where every woman can thrive and succeed.",
                            ISBN = "EWE202330",
                            ListPrice = 70.0,
                            Price = 60.0,
                            Price100 = 50.0,
                            Price50 = 55.0,
                            Title = "Empowering Women's Empowerment"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Parenting Guru",
                            CategoryId = 2,
                            Description = "Practice mindful parenting and foster a strong bond with your child. Navigate the joys and challenges of parenthood with awareness! This book is a guide to mindful parenting, providing practical tips and insights to raise emotionally intelligent and resilient children. Cultivate a deeper connection with your child and create a nurturing environment for their growth and development.",
                            ISBN = "MP202331",
                            ListPrice = 95.0,
                            Price = 85.0,
                            Price100 = 75.0,
                            Price50 = 80.0,
                            Title = "Mindful Parenting"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Sustainability Advocate",
                            CategoryId = 1,
                            Description = "Embrace eco-friendly living and make a positive impact on the planet. Discover sustainable practices for a greener future! This book is a roadmap to living a more eco-conscious life. Explore sustainable choices, from reducing waste to conserving energy, and learn how small changes can lead to a big difference in preserving our environment. Join the movement for a greener, cleaner planet.",
                            ISBN = "EFL202332",
                            ListPrice = 80.0,
                            Price = 70.0,
                            Price100 = 60.0,
                            Price50 = 65.0,
                            Title = "Eco-Friendly Living"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Financial Guru",
                            CategoryId = 3,
                            Description = "Take control of your finances and achieve financial freedom with our comprehensive blueprint. Secure your financial future! This guide is your blueprint to financial independence. Learn key principles of money management, investing, and wealth creation that will empower you to take control of your financial destiny. It's time to build a solid foundation for financial success.",
                            ISBN = "FFB202333",
                            ListPrice = 100.0,
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "Financial Freedom Blueprint"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Mindfulness Enthusiast",
                            CategoryId = 2,
                            Description = "Immerse yourself in the art of mindful living and find inner peace in the chaos of modern life. Cultivate mindfulness for a harmonious existence! This book is a guide to embracing mindfulness as a way of life. Explore mindfulness practices that will help you live in the present moment, reduce stress, and cultivate a sense of peace and balance in your daily life.",
                            ISBN = "AML202334",
                            ListPrice = 65.0,
                            Price = 55.0,
                            Price100 = 45.0,
                            Price50 = 50.0,
                            Title = "The Art of Mindful Living"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Happiness Scholar",
                            CategoryId = 1,
                            Description = "Unlock the secrets to happiness and lead a joyful, fulfilling life. Delve into the science and art of true happiness! This book explores the fascinating science behind happiness and offers actionable insights to help you cultivate happiness in your life. Discover the factors that contribute to a fulfilling life and embark on a journey towards a happier, more meaningful existence.",
                            ISBN = "SOH202335",
                            ListPrice = 75.0,
                            Price = 65.0,
                            Price100 = 55.0,
                            Price50 = 60.0,
                            Title = "The Science of Happiness"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Culinary Explorer",
                            CategoryId = 3,
                            Description = "Embark on a global culinary adventure and discover the diverse flavors of world cuisines. Expand your palate and tantalize your taste buds! This book is a gastronomic journey around the world, showcasing the vibrant and diverse flavors of various cuisines. From spicy curries to delicate pastries, immerse yourself in a world of taste sensations and culinary traditions.",
                            ISBN = "EWC202336",
                            ListPrice = 85.0,
                            Price = 75.0,
                            Price100 = 65.0,
                            Price50 = 70.0,
                            Title = "Exploring World Cuisines"
                        });
                });

            modelBuilder.Entity("Ecommerce.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage");
                });

            modelBuilder.Entity("Ecommerce.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCart");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CompanyId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Ecommerce.Models.OrderDetail", b =>
                {
                    b.HasOne("Ecommerce.Models.OrderHeader", "OrderHeader")
                        .WithMany()
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Models.OrderHeader", b =>
                {
                    b.HasOne("Ecommerce.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Ecommerce.Models.Product", b =>
                {
                    b.HasOne("Ecommerce.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ecommerce.Models.ProductImage", b =>
                {
                    b.HasOne("Ecommerce.Models.Product", "Product")
                        .WithMany("ProductImage")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Models.ShoppingCart", b =>
                {
                    b.HasOne("Ecommerce.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce.Models.ApplicationUser", b =>
                {
                    b.HasOne("Ecommerce.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Ecommerce.Models.Product", b =>
                {
                    b.Navigation("ProductImage");
                });
#pragma warning restore 612, 618
        }
    }
}
